name: Super-Liner

on: push 

jobs: 
  super-lint:
    name: Lint code based
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grants the token write access to repository contents
      statuses: write # Grants the token write access to commit statuses
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
